org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mantle_version=6635380
tic_version=6635554
jei_version=15.20.0.116
emi_version=1.1.22+1.20.1

mod_id=tic-hostility
mod_name=Tinkers Construct: Hostility
mod_license=MIT
mod_version=1.0.0
mod_group_id=yuuki1293.tichostility
mod_authors=yuuki1293
mod_description=
version_type=beta
